default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: boti
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: toptal_screening_development

production:
  <<: *default
  database: toptal_screening_production

test:
  <<: *default
  database: toptal_screening_test
